### ISSUE TITLE
WARNING: Logging before InitGoogleLogging() is written to STDERR

### ISSUE THREAD

**Issue by taolileyouyou** [rychien-official/payoff#1]
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1210 16:34:25.507810 16868 linear_solver.cc:426] Linear solver not recognized.
*** Check failure stack trace: ***

**Comment by ryan-chien** [comment]
Hi @taolileyouyou can you please provide a reproducible example for the error? Happy to look into it.

BR,
Ryan

**Comment by taolileyouyou** [comment]
The error has solved by install the Gurobi Optimization solver. The environment is not configured properly before.
thanks~
